server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mis_reporting
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB